openapi: 3.1.0
info:
  version: '0.1'
  title: OBapp
  description: |
    OBapp reference point.  
    © International Union of Railways (UIC) – Paris, 2024 
externalDocs:
  description: OBapp reference point
  url: https://uic.org/rail-system/telecoms-signalling/frmcs
servers:
  - url: '{apiRoot}/obapp/{apiVersion}'
    variables:
      apiRoot:
        default: https://obapp.uic.org
        description: apiRoot as defined in clause 9.5 of UIC FFFIS 
      apiVersion:
        default: v1.0
        description: version of the API (see clause 9.6 of UIC FFFIS)
tags:
  - name: version management
    description: Management of interface version
  - name: registration management
    description: Management of application registration
  - name: session management
    description: Management of application sessions
  - name: notification management
    description: Management of application notifications
  - name: keepalive management
    description: Management of keepalive endpoint for application

paths:
  /versions:
    servers:
      - url: '{apiRoot}/obapp'
        variables:
          apiRoot:
            default: https://obapp.uic.org
            description: apiRoot as defined in clause 9.5 of UIC FFFIS 
    get:
      summary: List of OBapp versions supported by the Onboard FRMCS
      description: |
        Operation used to list the OBapp versions supported by the Onboard FRMCS.
        Can be invoked without local registration
      operationId: listObAppVersion
      tags:
        - version management
      responses:
        '200':
          description: Successful operation - list major and minor versions of OBapp supported by the Onboard FRMCS 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationVersionsList"
              examples:
                ApplicationVersionsList:
                  value: ["1.0", "1.1", "2.0", "2.1", "3.0"]
                    
  /registrations:
    post:
      summary: Register an application
      operationId: registerApplication
      tags:
        - registration management
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterData'
            examples:
              RegisterData:
                value:
                  appCategory: ETCS
                  staticId: etcs-ob.etcs
                  couplingMode: loose
      responses:
        '201':
          description: Successful registration
          headers:
            Location:
              description: 'URI of the registered application instance'
              required: true
              schema:
                $ref: '#/components/schemas/Uri'
              examples:
                Location:
                  value: "https://192.168.1.254/obapp/v1.0/registrations/4210f20b-23e6-4354-bb1a-be4e0bc56f57"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisteredData'
              examples:
                registeredData:
                  summary: registration data example
                  value:
                    appObId: 4210f20b-23e6-4354-bb1a-be4e0bc56f57
                    selectedVersion: "1.0"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterErrorData'
              examples:
                registerErrorData:
                  summary: example error response for registration bad request
                  value:
                    resource: "https://192.168.1.254/obapp/v1.0/registrations"
                    cause: "ILL_FORMED_REQUEST"
                    detail: "the field couplingMode must be loose or tight"
        '403':
          description: Forbidden (unrecognized application, ...)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterErrorData'
              examples:
                registerErrorData:
                  summary: example error response for registration Forbidden
                  value:
                    resource: "https://192.168.1.254/obapp/v1.0/registrations"
                    cause: "UNAUTH_UNKNOWN_APP_CATEGORY"
                    detail: "the voice application cannot use the 'couplingMode' parameter with value 'loose'"

  /registrations/{DynamicId}:
    delete:
      summary: De-register an application
      operationId: deregisterApplication
      tags:
        - registration management
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/DynamicId'
          examples:
            dynamicId:
              summary: UUID associated to a successful registration
              value: 4210f20b-23e6-4354-bb1a-be4e0bc56f57
      responses:
        '204':
          description: No content (application deregistered)
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeRegisterErrorData'
              examples:
                deRegisterErrorData:
                  summary: example error response for unauthorized deregistration
                  value:
                    resource: "https://192.168.1.254/obapp/v1.0/registrations/4210f20b-23e6-4354-bb1a-be4e0bc56f57"
                    cause: UNREGISTERED
                    details: "Deregistration unauthorized; local binding required"
        '404':
          description: Application with {DynamicId} not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeRegisterErrorData'
              examples:
                deRegisterErrorData:
                  summary: example error response for deregistration of a registration not found  
                  value: 
                    resource: "https://192.168.1.254/obapp/v1.0/registrations/4210f20b-23e6-4354-bb1a-be4e0bc56f57"
                    cause: "NOT_FOUND"
                    details: "Application with {DynamicId} 4210f20b-23e6-4354-bb1a-be4e0bc56f57 not found for deregistration"

  /sessions/{DynamicId}:
    get:
      summary: List of sessions for an application
      operationId: listApplicationSessions
      tags:
        - session management
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/DynamicId'
          examples:
            DynamicId:
              summary: UUID associated to a successful registration
              value: 4210f20b-23e6-4354-bb1a-be4e0bc56f57
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionsListData'
              examples:
                SessionsListData:
                  value: ["ca7b8255-447b-416e-97ba-ee0cbd0a1652", "dc9b42be-6945-47ff-9158-7cce4c9e1580", "eaf35690-17df-4c3d-8f59-51dc1cc1525b" ]
        '401':
          description: Unauthorized, local binding required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionsListErrorData'
              examples:
                SessionsListErrorData:
                  summary: example error response for unauthorized sessions listing 
                  value:
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57"
                    cause: UNREGISTERED
                    details: "Sessions listing unauthorized; local binding required"
        '404':
          description: Application with {DynamicId} not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionsListErrorData'
              examples:
                SessionsListErrorData:
                  summary: example error response for sessions listing for a registration not found
                  value: 
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57"
                    cause: "NOT_FOUND"
                    details: "Application with {DynamicId} 4210f20b-23e6-4354-bb1a-be4e0bc56f57 not found for sessions listing"
    post:
      summary: Create a session for an application
      operationId: createApplicationSession
      tags:
        - session management
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/DynamicId'
          examples:
            DynamicId:
              summary: UUID associated to a successful registration
              value: 4210f20b-23e6-4354-bb1a-be4e0bc56f57
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OBSessionOpenData'
            examples:
              obSessionOpenDataIpV4:
                summary: example of open session data ipv4
                value:
                    localAppIPAddress:
                      ipv4Addr: "198.168.100.50"
                    recipientsList:
                      - remoteAddress: etcs-ts.etcs
                        communicationCategory: basic
              obSessionOpenDataIpV6:
                summary: example of open session data ipv6
                value:      
                    localAppIPAddress: 
                      ipv6Addr: "2001:db8:85a3::8a2e:370:7334"
                    recipientsList:
                      - remoteAddress: ato-ob.ato
                        communicationCategory: basic
      responses:
        '201':
          description: 'Session created'
          headers:
            Location:
              description: 'URI of the session which was opened'
              required: true
              schema:
                $ref: '#/components/schemas/Uri'
              examples:
                Location:
                  value: "https://192.168.1.254/obapp/v1.0/registrations/4210f20b-23e6-4354-bb1a-be4e0bc56f57/ca7b8255-447b-416e-97ba-ee0cbd0a1652"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionOpenedData'
              examples:
                sessionOpenedData:
                  summary: example of successful response for session opening   
                  value:
                    sessionId: ca7b8255-447b-416e-97ba-ee0cbd0a1652
                    sessionStatus: inProgress
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionOpenErrorData'
              examples:
                SessionOpenErrorData:
                  summary: example error response for session opening bad request
                  value:
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57"
                    cause: "ILL_FORMED_REQUEST"
                    detail: "Missing parameter"
        '401':
          description: Unauthorized, local binding required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionOpenErrorData'
              examples:
                SessionsListErrorData:
                  summary: example error response for unauthorized session opening 
                  value:
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57"
                    cause: UNREGISTERED
                    details: "Session opening unauthorized; local binding required"
        '403':
          description: Forbidden, session initiation not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionOpenErrorData'
              examples:
                SessionsListErrorData:
                  summary: example error response for unauthorized session opening 
                  value:
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57"
                    cause: UNAUTHORIZED
                    details: "Session opening unauthorized"
    delete:
      summary: Terminate all sessions for an application
      operationId: terminateApplicationSessions
      tags:
        - session management
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/DynamicId'
      responses:
        '204':
          description: No content (sessions terminated)
        '401':
          description: Unauthorized
        '404':
          description: Not found

  /sessions/{DynamicId}/{SessionId}:
    get:
      summary: Get information on a session of an application
      operationId: listApplicationSessionStatus
      tags:
        - session management
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/DynamicId'
          examples:
            DynamicId:
              summary: UUID associated to a successful registration
              value: 4210f20b-23e6-4354-bb1a-be4e0bc56f57
        - name: SessionId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/SessionId'
          examples:
            SessionId:
              summary: UUID associated to a session
              value: ca7b8255-447b-416e-97ba-ee0cbd0a1652
      responses:
        '200':
          description: Successful operation get information about a session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionStatusData'
              examples:
                sessionStatusData:
                  value:
                    sessionOriginator: localApplication
                    communicationCategory: basic
                    nextHopIPAddress:
                      ipv4Addr: 192.168.1.221
                    destApplicationIPAddress:
                      ipv4Addr: 172.16.5.1
                    remoteAddress: etcs-ts.etcs
        '401':
          description: Unauthorized, local binding required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionStatusErrorData'
              examples:
                SessionStatusErrorData:
                  summary: example error response for unauthorized session status listing
                  value:
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57/ca7b8255-447b-416e-97ba-ee0cbd0a1652"
                    cause: UNREGISTERED
                    details: "Session status listing unauthorized; local binding required"
        '404':
          description: Session {SessionId} not found for application {DynamicId}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionStatusErrorData'
              examples:
                SessionStatusErrorData:
                  summary: example error response for session status listing for a session not found
                  value: 
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57/ca7b8255-447b-416e-97ba-ee0cbd0a1652"
                    cause: "NOT_FOUND"
                    details: "Session with {SessionId} ca7b8255-447b-416e-97ba-ee0cbd0a1652 not found for sessions listing"
    put:
      summary: Respond to an incoming session request notification for an application
      operationId: answerApplicationIncomingSessionRequest
      tags:
        - session management
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/DynamicId'
          examples:
            DynamicId:
              summary: UUID associated to a successful registration
              value: 4210f20b-23e6-4354-bb1a-be4e0bc56f57
        - name: SessionId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/SessionId'
          examples:
            SessionId:
              summary: UUID associated to a session
              value: ca7b8255-447b-416e-97ba-ee0cbd0a1652
      requestBody:
        description: Request body to respond to an incoming session request 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IncomingSessionNotificationResponseData'
            examples:
              IncomingSessionNotificationResponseData:
               value:
                 appResponse: accepted
                 localAppIPAddress:
                    ipv4Addr: 198.50.200.1
      responses:
        '200':
          description: OK, sent if the application has accepted the incoming session request
          headers:
            Content-Location:
              description: 'URI of the session being established'
              required: true
              schema:
                $ref: '#/components/schemas/Uri'
              examples:
                Location:
                  value: "https://192.168.1.254/obapp/v1.0/registrations/4210f20b-23e6-4354-bb1a-be4e0bc56f57/ca7b8255-447b-416e-97ba-ee0cbd0a1652"
        '204':
          description: No content (acknowledgement of the application having declined the incoming session request)
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IncomingSessionNotificationResponseErrorData'
              examples:
                IncomingSessionNotificationResponseErrorData:
                  summary: example error response for incoming session response bad request
                  value:
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57/ca7b8255-447b-416e-97ba-ee0cbd0a1652"
                    cause: "ILL_FORMED_REQUEST"
                    details: "Incoming session response; missing parameter 'appResponse'"
        '401':
          description: Unauthorized, local binding required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IncomingSessionNotificationResponseErrorData'
              examples:
                IncomingSessionNotificationResponseErrorData:
                  summary: example error response for unauthorized incoming session response
                  value:
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57/ca7b8255-447b-416e-97ba-ee0cbd0a1652"
                    cause: UNREGISTERED
                    details: "Incoming session response unauthorized; local binding required"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IncomingSessionNotificationResponseErrorData'
              examples:
                IncomingSessionNotificationResponseErrorData:
                  summary: example error response for incoming session response for a session not found
                  value: 
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57/ca7b8255-447b-416e-97ba-ee0cbd0a1652"
                    cause: "NOT_FOUND"
                    details: "Session with {SessionId} ca7b8255-447b-416e-97ba-ee0cbd0a1652 not found"
          
    delete:
      summary: Terminate a session for an application
      operationId: terminateApplicationSession
      tags:
        - session management
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/DynamicId'
          examples:
            DynamicId:
              summary: UUID associated to a successful registration
              value: 4210f20b-23e6-4354-bb1a-be4e0bc56f57
        - name: SessionId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/SessionId'
          examples:
            SessionId:
              summary: UUID associated to a session
              value: ca7b8255-447b-416e-97ba-ee0cbd0a1652
      responses:
        '204':
          description: No content (session terminated)
        # TODO: consider possible rejection by the server of a session closure?
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionTerminateErrorData'
              examples:
                SessionTerminateErrorData:
                  summary: example error response for unauthorized session termination
                  value:
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57/ca7b8255-447b-416e-97ba-ee0cbd0a1652"
                    cause: UNREGISTERED
                    details: "Session termination unauthorized; local binding required"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionTerminateErrorData'
              examples:
                SessionTerminateErrorData:
                  summary: example error response for unauthorized session termination 
                  value:
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57"
                    cause: UNAUTHORIZED
                    details: "Session termination unauthorized"
  
  /notifications/{DynamicId}/events:
    get:
      summary: Subscribe to notification event stream for an application (SSE)
      operationId: subscribeApplicationNotificationEventStream
      tags:
        - notification management
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/DynamicId'
          examples:
            DynamicId:
              summary: UUID associated to a successful registration
              value: 4210f20b-23e6-4354-bb1a-be4e0bc56f57
      responses:
        '200':
          description: SSE notifications
          content:
            text/event-stream:
              schema:
                $ref: '#/components/schemas/EventStream'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventStreamErrorData'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventStreamErrorData'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventStreamErrorData'
              examples:
                EventStreamErrorData:
                  summary: example error response for event stream subscription for a {DynamicId} not found
                  value: 
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57/events"
                    cause: "NOT_FOUND"
                    details: "Application with {DynamicId} 4210f20b-23e6-4354-bb1a-be4e0bc56f57 not found"
              
                
  /notifications/{DynamicId}/channels:
    get:
      summary: Get information on subscriptions to notifications for an application
      operationId: listApplicationSubscriptions
      tags:
        - notification management
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/DynamicId'
          examples:
            DynamicId:
              summary: UUID associated to a successful registration
              value: 4210f20b-23e6-4354-bb1a-be4e0bc56f57
      responses:
        '200':
          description: Successful operation list subscriptions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionsListData'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionsListErrorData'
              examples:
                SubscriptionsListErrorData:
                  summary: example error response for unauthorized listing of subscriptions
                  value:
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57/channels"
                    cause: UNREGISTERED
                    details: "Listing of subscriptions unauthorized; local binding required"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionsListErrorData'
              examples:
                SubscriptionsListErrorData:
                  summary: example error response for unauthorized listing of subscriptions
                  value:
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57/channels"
                    cause: UNAUTHORIZED
                    details: "Listing of subscriptions unauthorized"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionsListErrorData'
              examples:
                SubscriptionsListErrorData:
                  summary: example error response for listing subscriptions for a {DynamicId} not found
                  value: 
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57/channels"
                    cause: "NOT_FOUND"
                    details: "Application with {DynamicId} 4210f20b-23e6-4354-bb1a-be4e0bc56f57 not found"
    delete:
      summary: Unsubscribe to all subscriptions to notifications for an application except for the general channel
      operationId: deleteApplicationSubscriptions
      tags:
        - notification management
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/DynamicId'
          examples:
            DynamicId:
              summary: UUID associated to a successful registration
              value: 4210f20b-23e6-4354-bb1a-be4e0bc56f57
      responses:
        '204':
          description: No content (subscriptions removal successful)
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionsRemovalErrorData'
              examples:
                SubscriptionsRemovalErrorData:
                  summary: example error response for unauthorized removal of subscriptions
                  value:
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57/channels"
                    cause: UNREGISTERED
                    details: "Removal of subscriptions unauthorized; local binding required"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionsRemovalErrorData'
              examples:
                SubscriptionsRemovalErrorData:
                  summary: example error response for unauthorized removal of subscriptions
                  value:
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57/channels"
                    cause: UNAUTHORIZED
                    details: "Removal of subscriptions unauthorized"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionsRemovalErrorData'
              examples:
                SubscriptionsRemovalErrorData:
                  summary: example error response for bulk unsubscriptions for a {DynamicId} not found
                  value: 
                    resource: "https://192.168.1.254/obapp/v1.0/sessions/4210f20b-23e6-4354-bb1a-be4e0bc56f57/channels"
                    cause: "NOT_FOUND"
                    details: "Application with {DynamicId} 4210f20b-23e6-4354-bb1a-be4e0bc56f57 not found"
    
  /notifications/{DynamicId}/{Channel}:
    get:
      summary: Subscribe to a specific channel for an application (SSE)
      operationId: subscribeApplicationNotificationChannel
      tags:
        - notification management
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/DynamicId'
        - name: Channel
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Channel'
      responses:
        '200':
          description: SSE notifications
          content:
            text/event-stream:
              schema:
                $ref: '#/components/schemas/EventStream'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DynamicChannelErrorData'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DynamicChannelErrorData'
    delete:
      summary: Unsubscribe to a specific channel for an application
      operationId: unsubscribeApplicationNotificationChannel
      tags:
        - notification management
      parameters:
        - name: DynamicId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/DynamicId'
        - name: Channel
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Channel'
      responses:
        '204':
          description: No content (channel unsubscribed)

  /keepalive:
    get:
      summary: Check the server is alive at the HTTP level
      operationId: checkKeepalive
      tags:
        - keepalive management
      responses:
        '204':
          description: No content (acknowledgement of the server being responsive on the control plane)

components:
  securitySchemes:
    clientCert:
      type: mutualTLS
  schemas:
    # FFFIS application and session identifiers
    DynamicId:
      description: "identifier of an application instance, dynamically assigned at registration. UUID v4."
      type: string
      format: uuid
      maxLength: 36
    SessionId:
      description: "identifier of an application session. UUID v4"
      type: string
      format: uuid
      maxLength: 36
    SubscriptionId:
      description: "identifier of an application subscription. UUID v4"
      type: string
      format: uuid
      maxLength: 36

    # IPv4 / IPv6 addresses
    # Aligned with 3GPP 29.571 Common Data yaml description
    Ipv4Addr:
      description: String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.
      type: string
      format: ipv4
      maxLength: 15
      pattern: '^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$'
      examples:
        - '198.51.100.1'
    Ipv6Addr:
      description: String identifying an IPv6 address formatted according to clause 4 of RFC5952.
      type: string
      format: ipv6
      # maxLength would theoretically be 39 but in some odd-case (IPv4-mapped IPv6 addresses), it could be up to 45 
      maxLength: 45
      allOf:
        - pattern: '^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))$'
        - pattern: '^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))$'
      examples:
        - '2001:db8:85a3::8a2e:370:7334'

    # IP address
    # Similar to 3GPP 29.571 Common Data yaml description (without ipv6Prefix which is not applicable in FRMCS FFFIS)
    IpAddr:
      description: Contains an IP adress.
      type: object
      oneOf:
        - required:
          - ipv4Addr
        - required:
          - ipv6Addr
      properties:
        ipv4Addr:
          $ref: '#/components/schemas/Ipv4Addr'
        ipv6Addr:
          $ref: '#/components/schemas/Ipv6Addr'

    # URI, aligned with 3GPP 29.571 Common Data yaml description
    Uri:
      description: String providing an URI formatted according to RFC 3986.
      type: string
      format: uri

    # event stream
    EventStream:
      description: Server sent events model
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 0
        event:
          type: string
          # TODO: could be constrained to an enumeration once we have all event names identified 
        data:
          oneOf:
            - $ref: "#/components/schemas/GeneralChannelEventStreamData"
            - $ref: "#/components/schemas/LocationChannelEventStreamData"

    EventStreamErrorData:
      description: Data in case of SSE subscription error
      type: object
      oneOf:
        - $ref: '#/components/schemas/GenericErrorData'
        
    GeneralChannelEventStreamData:
      description: data on general event stream
      type: object

    LocationChannelEventStreamData:
      description: data on general event stream
      type: object

    # FQDN, aligned with 3GPP 29.571 Common Data yaml description
    Fqdn:
      description: Fully Qualified Domain Name
      type: string
      pattern: '^([0-9A-Za-z]([-0-9A-Za-z]{0,61}[0-9A-Za-z])?\.)+[A-Za-z]{2,63}\.?$'
      minLength: 4
      maxLength: 253

    # FFFIS enums

    # TODO: is a closed list enumeration the right thing to do if the FRMCS framework foresees that applications could be added
    # Ultimately, the ApplicationCategory serves to retrieve from the FOAP the parameters associated to the application
    # In the context of railway interoperability, there shall be harmonized application categories but the schema shall allow for non-harmonized extensions
    # which would allow for IM-specific non-interoperable applications (Type II) and RU-specific non-interoperable applications (that would be subject to use where 
    # IMs within the area of use authorize it 
    ApplicationCategory:
      description: Provides the category of the Application (e.g., ETCS, ATO, FRMCS Voice Application Function, TCMS, etc.). 
        When applicable, this parameter is used to link the registration to the necessary 3GPP MCX service(s).
      type: string
      enum:
        - CategoryA
        - CategoryB
        - CategoryC

    # TODO: a multipart schema would be preferable over a single string as this would facilitate the usage of mapping rules when
    # generating the MC Service User ID associated to a given application 
    # Note: as it helps with establishing identity within the MCX framework, it may actually be more representative of the identification of an 
    # application instance or the service user associated to the application than the application itself. 
    ApplicationStaticIdentifier:
      description: Unique identifier of the Application.
      type: string

    # Versioning of the interface 
    ApplicationVersion:
      type: string
      pattern: '^(\d+\.\d+)$'
      description: Semantic version of the application (e.g., 1.0)
      examples:
        - '1.0'
      minLength:  3

    ApplicationVersionsList:
      description: list of versions supported by the application 
      type: array
      items:
        $ref: "#/components/schemas/ApplicationVersion"
      minItems: 1
      
    Channel:
      description: Channel of notification
      type: string
      enum:
        - general
        - location
        - time
      default: general
      
    CouplingMode:
      description: >
        The application coupling mode.
        Possible values:
          - tight for Tight Coupled mode
          - loose for Loose Coupled mode
      type: string
      enum:
        - tight
        - loose
      default: loose

    DataComm:
      description: "The data communication mode is used by the Communication category parameter. It reflects the possible values applicable to this mode: basic or criticale"
      type: string
      enum:
        - basic
        - critical
      default: basic
    
    DynamicChannelErrorData:
      description: Data in case of SSE subscription error
      type: object
      oneOf:
        - $ref: '#/components/schemas/GenericErrorData'
        
    # Inspired from ProblemDetails in 3GPP 29.571
    GenericErrorData:
      description: Provides additional information in an error response.
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/Uri'
        cause:
          type: string
          description: >
            A machine-readable application error cause specific to this occurrence of the problem. 
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
          
    IncomingSessionAppResponse:
      description: application response to an incoming session request
      type: string
      enum:
        - accepted
        - rejected
    
    RemoteAddress:
      description: "Remote address of an application in the scope of session exchange messages"
      type: string
      minLength: 3
      maxLength: 255

    SessionStartReqFirstStatus:
      description: "Provides the first status of a Session start request. This parameter is used in the Session start first answer message"
      type: string
      enum:
        - inProgress
        - networkNotReady
        - notRegistered
        - rejected
      default: inProgress
        
    VideoComm:
      description: "The video communication mode is used by the Communication category parameter. It reflects the possible values applicable to this mode: basic or critical."
      type: string
      enum:
        - basic
        - critical
      default: basic

    # FFFIS payloads
    CommunicationCategory:
      description: "This parameter reflects the different categories of communication (session) that can be established over the FRMCS according to the [FRMCS FRS]. This parameter is used by the On-Board FRMCS to initiate an end-to-end session. Based on this parameter, the On-Board FRMCS assigns the right communication profile including the QoS level to the session."
      type: object
      oneOf:
        - $ref: "#/components/schemas/DataComm"
        - $ref: "#/components/schemas/VideoComm"
      default: "basic"

    DeRegisterErrorData:
      description: Data in case of registration error
      type: object
      oneOf:
        - $ref: '#/components/schemas/GenericErrorData'
      
    IncomingSessionNotificationResponseData:
      description: Response to an incoming session notification
      type: object
      properties:
        appResponse:
          $ref: "#/components/schemas/IncomingSessionAppResponse"
        localAppIPAddress:
          $ref: '#/components/schemas/IpAddr'

    IncomingSessionNotificationResponseErrorData:
      description: Data in case of error when responding to an incoming session notification
      type: object
      oneOf:
        - $ref: '#/components/schemas/GenericErrorData'

    Recipient:
      description: "Recipient"
      type: object
      properties:
        remoteAddress:
          $ref: "#/components/schemas/RemoteAddress"
        communicationCategory:
          $ref: "#/components/schemas/CommunicationCategory"
    
    RecipientsList:
      description: "List of Recipients"
      type: array
      items:
        $ref: "#/components/schemas/Recipient"
        
    RegisterData:
      description: Registration data input
      type: object
      properties:
        appCategory:
          $ref: '#/components/schemas/ApplicationCategory'
        staticId:
          $ref: '#/components/schemas/ApplicationStaticIdentifier'
        supportedVersionsList:
          $ref: '#/components/schemas/ApplicationVersionsList'
        couplingMode:
          $ref: '#/components/schemas/CouplingMode'

    RegisteredData:
      description:  Registration data output
      type: object
      properties:
        appObId:
          $ref: '#/components/schemas/DynamicId'
        selectedVersion:
          $ref: '#/components/schemas/ApplicationVersion'

    RegisterErrorData:
      description: Data in case of registration error
      type: object
      oneOf:
        - $ref: '#/components/schemas/GenericErrorData'

    OBSessionOpenData:
      description: Session opening data input (OBapp)
      type: object
      properties:
        localAppIPAddress:
          $ref: '#/components/schemas/IpAddr'
        recipientsList:
          type: array
          items:
            $ref: '#/components/schemas/Recipient'
          minItems: 1
          maxItems: 1
          
    # TODO: kept for now as TSapp equivalent could use a cardinality of recipients > 1
    SessionOpenData:
      description: Session opening data input
      type: object
      properties:
        localAppIPAddress:
          $ref: '#/components/schemas/IpAddr'
        recipientsList:
          $ref: '#/components/schemas/RecipientsList'

    SessionOpenedData:
      description:  Session opening data output
      type: object
      properties:
        sessionId:
          $ref: '#/components/schemas/SessionId'
        sessionStatus:
          $ref: '#/components/schemas/SessionStartReqFirstStatus'

    SessionOpenErrorData:
      description: Data in case of error when opening a session
      type: object
      oneOf:
        - $ref: '#/components/schemas/GenericErrorData'

    # TODO: clarify as, theoretically, there could be more than one recipient...
    SessionStatusData:
      description: information about a session
      type: object
      properties:
        sessionOriginator:
          type: object
        communicationCategory:
          $ref: "#/components/schemas/CommunicationCategory"
        localDestFRMCSIPAddress:
          $ref: '#/components/schemas/IpAddr'
        destApplicationIPAddress:
          $ref: '#/components/schemas/IpAddr'
        remoteAddress:
          type: object

    SessionStatusErrorData:
      description: Data in case of error when fetching a session status
      type: object
      oneOf:
        - $ref: '#/components/schemas/GenericErrorData'

    SessionsListData:
      description: list of sessions
      type: array
      items:
        $ref: '#/components/schemas/SessionId'

    SessionsListErrorData:
      description: Data in case of error when listing sessions for an application
      type: object
      oneOf:
        - $ref: '#/components/schemas/GenericErrorData'
        
    SessionTerminateErrorData:
      description: Data in case of error when terminating a session
      type: object
      oneOf:
        - $ref: '#/components/schemas/GenericErrorData'

    SubscriptionData:
      description: subscription data for a channel other than general
      type: object
      properties:
        subscriptionId:
          $ref: '#/components/schemas/SubscriptionId'
        channel:
          $ref: '#/components/schemas/Channel'
        parameters:
          type: object
    
    SubscriptionsListData:
      description: list of subscriptions data
      type: array
      items:
        $ref: '#/components/schemas/SubscriptionData'
        
    SubscriptionsListErrorData:
      description: Data in case of error when listing subscriptions for an application
      type: object
      oneOf:
        - $ref: '#/components/schemas/GenericErrorData'
    SubscriptionsRemovalErrorData:
      description: Data in case of error when removing subscriptions for an application
      type: object
      oneOf:
        - $ref: '#/components/schemas/GenericErrorData'

    VersionsErrorData:
      description: Data in case of error when requestuion supported versions
      type: object
      oneOf:
        - $ref: "#/components/schemas/GenericErrorData"
